apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-world
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: go-hello-world
  template:
    metadata:
      labels:
        app: go-hello-world
    spec:
      containers:
      - image: harbor.shared.12factor.xyz/bglover/go-hello-world@sha256:6a5428adad212483c7eec133b6d69680bdf1c62d7d300a74a71b05fc67777377
        name: go-hello-world
        ports:
        - containerPort: 8080
